language: cpp

sudo: required

os:
    - linux
    - osx

compiler:
    - gcc

env:
    - BUILD_TYPE=Release

before_script:
    - cd $TRAVIS_BUILD_DIR/..
    - git clone -b 4.9.2 --depth=1 https://github.com/osgeo/proj.4 proj-4
    - cd proj-4
    - mkdir build
    - cd build 
    - cmake -DBUILD_TESTING=OFF -DBUILD_PROJ4_TESTS=OFF ../
    - cmake --build . --config Release
    - sudo cmake --build . --config Release --target install
    - export PROJ4_INCLUDE_DIR=$PWD/../src
    - export PROJ4_LIB_DIR=$PWD/lib
    - cd $TRAVIS_BUILD_DIR
    - mkdir build/


script:
    - cd build/
    - cmake -DCMAKE_CXX_FLAGS=$MOOS_CXX_FLAGS ../
    - cmake --build . --config Release

after_script:
    - sudo cmake --build . --config Release --target install

cache:
    directories:
    -$TRAVIS_BUILD_DIR/../proj-4